### PR TITLE
#5 Add placeholders for ice40 tutorial

### LINKED ISSUE #5: Add tutorial for ice40 feather
Adapt existing tutorials format for iCE40-Feather.

### PR DESCRIPTION
**Pull request by whatnick**
Closes #5 
Signed-off-by: Tisham Dhar <whatnickd@gmail.com>

### CODE REVIEW

**Comment by wuxx** [comment]
some days ago I try to build it on my ice40up5k board, and it report failure, here is the error log on this commit, it seems that the SB_PLL40_CORE primitive don't allow use pin 35 (from BANK0) as the input source clk, but I reference the lattice technical document it says IO from BANK2 is not allowed. but pin 35 is from BANK0, it strange, may be the toolchain not support yet?
image

----------------
ERROR: PLL 'pll.pll' couldn't be placed anywhere, no suitable BEL found. Did you mean to use a PAD PLL ?

Info: Annotating ports with timing budgets for target frequency 12.00 MHz
ERROR: cell type 'SB_PLL40_CORE' is unsupported (instantiated as 'pll.pll')
26 warnings, 2 errors
Makefile:71: recipe for target 'ICEFEATHER.synth' failed
----------------

**Comment by whatnick** [comment]
> some days ago I try to build it on my ice40up5k board, and it report failure, here is the error log on this commit, it seems that the SB_PLL40_CORE primitive don't allow use pin 35 (from BANK0) as the input source clk, but I reference the lattice technical document it says IO from BANK2 is not allowed. but pin 35 is from BANK0, it strange, may be the toolchain not support yet?
> image
> 
> ERROR: PLL 'pll.pll' couldn't be placed anywhere, no suitable BEL found. Did you mean to use a PAD PLL ?
> 
> ## Info: Annotating ports with timing budgets for target frequency 12.00 MHz
> ERROR: cell type 'SB_PLL40_CORE' is unsupported (instantiated as 'pll.pll')
> 26 warnings, 2 errors
> Makefile:71: recipe for target 'ICEFEATHER.synth' failed

My attempts are at exactly this road-block. Glad I have a few people following along and hopefully this PR can be merged as a first cut of WIP for up5k support.

**Comment by wuxx** [comment]
one solution is use the SB_PLL40_PAD instead of  SB_PLL40_CORE

**Comment by whatnick** [comment]
Core PLL is used in a few places and will need a refactor. 
image

**Comment by BrunoLevy** [comment]
- added a PASSTHROUGH_PLL configuration in RTL/femtosoc_config.v and updated TUTORIALS/newboard.md accordingly
- @whatnick, the instances of SB_PLL40_CORE that you found in Basic are not used in femtorv32 (there is a single instance, it is in RTL/DEVICES/femtopll.v)
- From what I have read, it will probably work by replacing SB_PLL40_CORE with SB_PLL40_PAD in femtopll.v, would one of you guys give it a try ?

**Comment by wuxx** [comment]
ok，waiting for the commit :-)

**Comment by wuxx** [comment]
just try the latest code on my ice40up5k board, 
1. the nexpnr told the max freq is about 20MHz, so I config the  NRF_FREQ to 18MHz
Info: Max frequency for clock 'clk_$glb_clk': 19.44 MHz (PASS at 12.00 MHz)
2. the reset pin is tied to GND
3. after programmed, open the serial port with baudrate 115200, but nothing show. did I miss something ?

**Comment by wuxx** [comment]
few days ago I work on the commit fbafcceb2a582bdfff59f643a6ea5785049956dc and do a modify with FemtoRV/FIRMWARE/LIBFEMTORV32/femtorv32.h
-#define CONFIGWORD_DEVICES        3
+#define CONFIGWORD_DEVICES       2

it can succ log on serial port

**Pull request merged**
