### PR TITLE
Icesugar-nano flash

### PR DESCRIPTION
**Pull request by abderraouf-adjal**
Fix issues in scripting, and add the support of running from flash for the dev board icesugar-nano.

details to run `hello.c`:

```
% make ICESUGAR_NANO
% cd FemtoRV/FIRMWARE/EXAMPLES
% make hello.prog
```

### CODE REVIEW

**Comment by abderraouf-adjal** [comment]
@BrunoLevy Hello, this chain of improvements are working fine in my end for icesugar-nano (ice40lp1k). I don't know if anyone has the same board to test it too. The CPU is running from the SPI flash very well.

Maybe @wuxx the maker of that board can help testing?

**Comment by Chandler-Kluser** [comment]
@abderraouf-adjal, when I cloned your fork these files didn't come along with I don't know why.

But I have tested in my icesugar-nano board. The linebreaks didn't work as expected, but it works!!

uart-hello-icesugar-nano

**Comment by abderraouf-adjal** [comment]
@Chandler-Kluser I didn't understand if you are saying the patch doesn't work or no.
If the only issue is the new line breaks maybe it's related to the UART application, try something else like the one from Arduino IDE or gtkterm, you can easily choose the new line char mode (unix, ms-windows, mac)

**Comment by Chandler-Kluser** [comment]
It does work!!

about the UART: tried putty and screen, I had the same outputs

**Comment by abderraouf-adjal** [comment]
@Chandler-Kluser  Use "gtkterm", select the right port, then from menu: "Configuration -> CR LF Auto". You have to tell the serial apps what line ending is being used.

**Pull request merged**
